from unittest.mock import MagicMock

import pytest

from google_sheets import (
    CASE_HISTORY_SHEET_NAME,
    CASE_SHEET_NAME,
    build_case_history_rows,
    build_case_rows,
    determine_approval_status,
    normalize_whatsapp_name,
    resolve_role_display_name,
    sync_all_to_google_sheets,
)


def test_role_mapping_and_name_normalization():
    assert normalize_whatsapp_name("Mehta Ji SPM Dv Bsp Site") == "mehta"
    assert normalize_whatsapp_name("Gagan Deep Singh") == "gagan deep singh"
    assert resolve_role_display_name("Mehta Ji SPM Dv Bsp Site", "ADD GENERAL MANAGER") == "Mehta Sir"
    assert resolve_role_display_name("Gagan Deep Singh", "CLUSTER HEAD") == "Gagan Sir"
    assert resolve_role_display_name("Unknown Name", "DIRECTOR") == "Unknown Name"


def test_approval_summary_row_and_status_values():
    case = {
        "covering_number": "259",
        "description": "Payment request",
        "first_seen": "2026-08-01T09:00:00Z",
        "updated_at": "2026-08-02T00:00:00Z",
    }
    participants = [
        {"person": "Mukesh", "status": "APPROVED"},
        {"person": "Mehta Ji SPM Dv Bsp Site", "status": "APPROVED"},
        {"person": "Jagga Rao Sir", "status": "APPROVED"},
        {"person": "Gagan Deep Singh", "status": "APPROVED"},
        {"person": "Deep Patel Sir", "status": "APPROVED"},
    ]
    messages = [{"timestamp": "2026-08-01T09:00:00Z", "sender": "Utpal Singh", "text": "Case 259 generated"}]

    rows = build_case_rows([case], participants, messages)
    approval_row = rows[1]

    assert rows[0] == [
        "Case No.",
        "Description",
        "Project Manager",
        "Add General Manager",
        "GENERAL MANAGER",
        "CLUSTER HEAD",
        "DIRECTOR",
        "Approval Status",
        "First Generated",
    ]
    assert approval_row[0] == "259"
    assert approval_row[2] == "🟩 Mukesh Sir"
    assert approval_row[3] == "🟩 Mehta Sir"
    assert approval_row[4] == "🟩 Jagga Sir"
    assert approval_row[5] == "🟩 Gagan Sir"
    assert approval_row[6] == "🟩 Deep Sir"
    assert approval_row[7] == "🟢"
    assert approval_row[8] == "01-08-26 09:00"


def test_case_history_uses_fifth_approval_timestamp_and_pending_has_no_fake_finalization():
    case = {"covering_number": "259", "description": "Payment request", "first_seen": "2026-08-01T09:00:00Z"}
    first_approval_messages = [
        {"timestamp": "2026-08-01T09:05:00Z", "sender": "Utpal Singh", "text": "Case 259 opened"},
        {"timestamp": "2026-08-01T09:10:00Z", "sender": "Mukesh", "text": "Approved"},
        {"timestamp": "2026-08-01T09:15:00Z", "sender": "Mehta Ji SPM Dv Bsp Site", "text": "Approved"},
        {"timestamp": "2026-08-01T09:20:00Z", "sender": "Jagga Rao Sir", "text": "Approved"},
        {"timestamp": "2026-08-01T09:25:00Z", "sender": "Gagan Deep Singh", "text": "Approved"},
        {"timestamp": "2026-08-01T09:30:00Z", "sender": "Deep Patel Sir", "text": "Approved"},
    ]

    rows = build_case_history_rows(case, first_approval_messages)
    flattened = "\n".join(str(cell) for row in rows for cell in row if cell is not None)

    assert "CASE NO: 259" in flattened
    assert "Generated by: Utpal Singh" in flattened
    assert "Time: 09:30" in flattened
    assert "Status: APPROVED" in flattened
    assert "Date: 01-08-26" in flattened

    pending_case = {"covering_number": "261", "description": "Pending case", "first_seen": "2026-08-01T10:00:00Z"}
    pending_rows = build_case_history_rows(pending_case, [
        {"timestamp": "2026-08-01T10:02:00Z", "sender": "Utpal Singh", "text": "Case 261 opened"},
        {"timestamp": "2026-08-01T10:05:00Z", "sender": "Mukesh", "text": "Approved"},
    ])
    pending_flattened = "\n".join(str(cell) for row in pending_rows for cell in row if cell is not None)
    assert "Status: PENDING" in pending_flattened
    assert "Finalized:" not in pending_flattened or "Date:" not in pending_flattened.split("Finalized:")[-1]


def test_case_history_uses_normalized_display_names_for_mapped_contacts():
    case = {"covering_number": "778", "description": "Mapped approvals", "first_seen": "2026-08-09T10:00:00Z"}
    messages = [
        {"timestamp": "2026-08-09T10:00:00Z", "sender": "Utpal Singh", "text": "Case 778 generated"},
        {"timestamp": "2026-08-09T10:03:00Z", "sender": "Mehta Ji SPM Dv Bsp Site", "text": "Approved"},
        {"timestamp": "2026-08-09T10:04:00Z", "sender": "Gagan Deep Singh", "text": "Approved"},
    ]

    rows = build_case_history_rows(case, messages)
    flattened = "\n".join(str(cell) for row in rows for cell in row if cell is not None)

    assert "Mehta Sir" in flattened
    assert "Gagan Sir" in flattened
    assert "Utpal Singh" in flattened


def test_approval_status_color_thresholds():
    assert determine_approval_status(0) == "🔴"
    assert determine_approval_status(2) == "🟡"
    assert determine_approval_status(5) == "🟢"


def test_sync_all_to_google_sheets_writes_summary_and_history(monkeypatch):
    service = MagicMock()
    workbook = {
        "sheets": [
            {"properties": {"title": "Sheet1", "sheetId": 1}},
            {"properties": {"title": "Participants", "sheetId": 2}},
            {"properties": {"title": "Messages", "sheetId": 3}},
            {"properties": {"title": "Cases", "sheetId": 4}},
            {"properties": {"title": "Case History", "sheetId": 5}},
        ]
    }

    def mock_batch_update(*args, **kwargs):
        body = kwargs.get("body", {})
        for request in body.get("requests", []):
            if "deleteSheet" in request:
                sheet_id = request["deleteSheet"]["sheetId"]
                workbook["sheets"] = [
                    sheet for sheet in workbook["sheets"]
                    if sheet.get("properties", {}).get("sheetId") != sheet_id
                ]
        return MagicMock()

    service.spreadsheets().get().execute.side_effect = lambda *args, **kwargs: workbook
    service.spreadsheets().batchUpdate.side_effect = mock_batch_update
    spreadsheet_id = "spreadsheet-123"

    cases = [{
        "id": "case-259",
        "covering_number": "259",
        "description": "Payment request",
        "first_seen": "2026-08-01T09:00:00Z",
        "updated_at": "2026-08-02T00:00:00Z",
    }]
    participants = [{"person": "Mukesh", "status": "APPROVED"}]
    messages = [{"timestamp": "2026-08-01T09:00:00Z", "sender": "Utpal Singh", "text": "Case 259 generated"}]
    database_client = object()
    used_clients = []

    monkeypatch.setenv("GOOGLE_SHEETS_SPREADSHEET_ID", spreadsheet_id)
    monkeypatch.setattr("google_sheets.get_supabase_client", lambda: database_client)
    monkeypatch.setattr("google_sheets.get_cases", lambda client: used_clients.append(client) or cases)
    monkeypatch.setattr("google_sheets.get_participants", lambda client, case_id: used_clients.append(client) or participants)
    monkeypatch.setattr("google_sheets.get_messages", lambda client, case_id: used_clients.append(client) or messages)
    monkeypatch.setattr("google_sheets.get_sheets_service", lambda: service)

    sync_all_to_google_sheets()

    assert used_clients == [database_client, database_client, database_client, database_client]
    assert service.spreadsheets().batchUpdate.call_count >= 2
    assert service.spreadsheets().values().update.call_count >= 2

    sheet_names = []
    delete_requests = []
    for call in service.spreadsheets().batchUpdate.call_args_list:
        body = call.kwargs.get("body", {})
        requests = body.get("requests", [])
        for request in requests:
            if "deleteSheet" in request:
                delete_requests.append(request)

    assert delete_requests
    assert CASE_SHEET_NAME == "Cases"
    assert CASE_HISTORY_SHEET_NAME == "Case History"


def test_cases_sheet_formatting_is_bold_headers_and_centered_status_no_fill(monkeypatch):
    service = MagicMock()
    spreadsheet_id = "spreadsheet-123"
    monkeypatch.setenv("GOOGLE_SHEETS_SPREADSHEET_ID", spreadsheet_id)

    service.spreadsheets().get().execute.return_value = {
        "sheets": [{"properties": {"title": "Cases", "sheetId": 42}, "conditionalFormatRules": []}]
    }

    from google_sheets import _apply_approval_status_formatting

    _apply_approval_status_formatting(service, spreadsheet_id, "Cases")

    batch_body = service.spreadsheets().batchUpdate.call_args.kwargs["body"]
    requests = batch_body["requests"]
    assert any(
        req.get("repeatCell", {}).get("cell", {}).get("userEnteredFormat", {}).get("textFormat", {}).get("bold") is True
        for req in requests
    )
    assert any(
        req.get("repeatCell", {}).get("range", {}).get("startColumnIndex") == 7
        and req.get("repeatCell", {}).get("cell", {}).get("userEnteredFormat", {}).get("horizontalAlignment") == "CENTER"
        for req in requests
    )
    assert any(
        req.get("repeatCell", {}).get("range", {}).get("startColumnIndex") == 7
        and req.get("repeatCell", {}).get("cell", {}).get("userEnteredFormat", {}).get("backgroundColor") == {"red": 1.0, "green": 1.0, "blue": 1.0}
        for req in requests
    )

